name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Xcode tools
      run: |
        xcode-select -p || sudo xcode-select --install
        sudo xcodebuild -license accept

    - name: Install dependencies
      run: |
        # 设置macOS编译环境
        export SDKROOT=$(xcrun --show-sdk-path)
        export CFLAGS="-I$SDKROOT/usr/include"
        
        # 安装所有必需依赖
        pip install pyinstaller==6.15.0
        pip install flask requests jinja2 werkzeug pywebview
        # 统一版本避免冲突
        pip install pyobjc-core==11.1 pyobjc-framework-Cocoa==11.1 pyobjc-framework-WebKit==11.1 pyobjc-framework-Quartz==11.1 pyobjc-framework-security==11.1

    - name: Build application
      run: |
        pyinstaller macos_spec.spec

    - name: Check if app was built
      run: |
        # 检查应用是否生成（使用英文名称）
        if [ -d "dist/CF-MTG Automation.app" ]; then
          echo "应用已生成"
          ls -la "dist/CF-MTG Automation.app/"
        else
          echo "应用未生成，查看dist目录内容："
          ls -la dist/ || echo "dist目录不存在"
          exit 1
        fi

    - name: Create DMG
      run: |
        # 使用正确的应用名称创建DMG
        hdiutil create -volname "CF-MTG Automation" \
          -srcfolder "dist/CF-MTG Automation.app" \
          -ov -format UDZO \
          "dist/CF-MTG-Automation.dmg"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-App
        path: dist/CF-MTG-Automation.dmg